apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: rebuild
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/jeremiaswerner/rebuild@sha256:ff83eeb5c7943e4565db6e604069e001a7e644faf2e3c96b270f050327d2a177
            env:
            - name: SERVICE
              value: "helloworld"
          containerConcurrency: 1
